title: Sito-ITA
email: pfrancecsop252@gmail.com
description: >-
    
baseurl: ""
url: ""

kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-leaflet

photos:
  photo_repo: "s7uck/photos"
  output_url: "foto"
  ## UNCOMMENT FOR TESTING
  #remote_exif_url: "https://pastebin.com/raw/DsAnyFKz"
  location_map_url: "https://raw.githubusercontent.com/s7uck/photos/master/LOCATION.json"

defaults:
  - scope:
      path: ""
    values:
      links:
        links_out: "/links-out"
        curriculum: "/cve"
        foto: "/gallery"
        video: "/video"
        contatti: "/contatti"
